# The overall format is standard TOML format, v0.5.0: https://github.com/toml-lang/toml

# Mandatory: The name of the mod loader type to load
modLoader = "javafml"

# Mandatory: A version range to match for said mod loader
loaderVersion = "[44,)"

# Mandatory: The license for your mod
# Review your options at https://choosealicense.com/; all rights reserved is the default copyright stance, and is thus the default here
license = "CC0-1.0"

# Optional: A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/ChampionAsh5357/minecraft-multlingual-examples/issues"

# Mandatory: A list of mods
[[mods]]

# Mandatory: The modid of the mod
modId = "multilingual_examples"

# Mandatory: The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# file.jarVersion will substitute the value of the 'Implementation-Version' as read from the mod's JAR file metadata
version = "${version}"

# Mandatory: A display name for the mod
displayName = "Multlingual Examples - Forge Java"

# Optional: A URL to query for updates for this mod
# See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
# updateJSONURL = ""

# Optional: A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://github.com/ChampionAsh5357/minecraft-multlingual-examples"

# Optional: A file name (in the root of the mod JAR) containing a logo for display
# logoFile = ""

# Optional: A text field displayed in the mod UI
credits = "Minecraft, MinecraftForge, and Java"

# Optional: A text field displayed in the mod UI
authors = "ChampionAsh5357"

# Mandatory: The description text for the mod (multi line!)
description = '''
An example mod for Minecraft 1.19.x in the Java programming language via the Forge Mod Loader.
'''

# Optional: A dependency for your mod to rely on, use the '.' to indicate dependency for a specific modid
[[dependencies.multilingual_examples]]
    # Mandatory: The modid of the dependency
    modId = "forge"

    # Mandatory: Does this dependency have to exist
    mandatory = true

    # Mandatory: The version range of the dependency
    versionRange = "[44,)"

    # Mandatory: An ordering relationship for the dependency
    ordering = "NONE"

    # Mandatory: Side this dependency is applied on
    side = "BOTH"

[[dependencies.multilingual_examples]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3]"
    ordering = "NONE"
    side = "BOTH"
